# -*- coding: utf-8 -*-
"""nnfromscratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IAkbk24SwBlhwvuOepTXChCNZIxU4Sss
"""

import numpy as np
import pandas as pd

data = pd.read_csv('/content/sample_data/mnist_train_small.csv', header=None)
print(data.sample(5))
data = np.array(data)
m, n = data.shape
# the zeroth row depicts the outcome of a 28*28 picture
np.random.shuffle(data)
data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:]
X_dev = X_dev / 255.0
data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:]
X_train = X_train / 255.0

def init_params():
    W1 = (np.random.rand(10, 784) - 0.5) * 0.1
    b1 = (np.random.rand(10, 1) - 0.5) * 0.1
    W2 = (np.random.rand(10, 10) - 0.5) * 0.1
    b2 = (np.random.rand(10, 1) - 0.5) * 0.1
    return W1, b1, W2, b2
    # same as random weight as initiated in a llm for every word later the are adjusted using gradient discent

# activation and normalization functions

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):

    exp_Z = np.exp(Z - np.max(Z, axis=0, keepdims=True))
    return exp_Z / np.sum(exp_Z, axis=0, keepdims=True)
def ReLU_deriv(Z):
    return Z > 0

# just to code 7 in another way .....example 7 would be written in a array as [0,0,0,0,0,0,0,1,0,0,0]
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    return one_hot_Y.T

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def back_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    m = Y.size
    one_hot_Y = one_hot(Y)

    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2, axis=1, keepdims=True)

    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1, axis=1, keepdims=True)

    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)

        if i % 50 == 0:
            print(f"Iteration: {i}")
            predictions = get_predictions(A2)
            print(f"Accuracy: {get_accuracy(predictions, Y):.4f}")
            print("-------------------------")

    return W1, b1, W2, b2



W1, b1, W2, b2 = gradient_descent(X_train, Y_train, alpha=0.10, iterations=500)



import matplotlib.pyplot as plt

def test_prediction(index, W1, b1, W2, b2, X_dev, Y_dev):
    current_image = X_dev[:, index, None]
    label = Y_dev[index]

    Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, current_image)
    prediction = get_predictions(A2)

    print(f"Prediction: {prediction[0]}")
    print(f"Actual Label: {label}")

    current_image_reshaped = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image_reshaped, interpolation='nearest')
    plt.show()


i=int(input("enter a random choice of test data set "))
test_prediction(i, W1, b1, W2, b2, X_dev, Y_dev)

